# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Auto Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Build with Maven
      run: | 
        cd mavenProject
        mvn install
    - name: Update project's binaries
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Required
        commit_message: Update project's binaries

        # Optional options appended to `git-commit`
        commit_options: '--allow-empty'

        # Optional commit user and author settings
        commit_user_name: Stamacoding's Maven Bot
        commit_user_email: maven-bot@stamacoding.bot
        commit_author: Stamacoding's Maven Bot <maven-bot@stamacoding.bot>

        push_options: '--force'

        # Optional: Disable dirty check and always try to create a commit and push
        skip_dirty_check: true
